import org.apache.tools.ant.filters.ReplaceTokens

import java.time.Instant

plugins {
	id "architectury-plugin" version "3.4.160"
	id "dev.architectury.loom" version "1.9.424" apply false
	id "de.undercouch.download" version "4.1.2"
	id "com.github.johnrengelman.shadow" version "8.1.1"
	id "io.github.pacifistmc.forgix" version "1.2.9"
	id "base"
}

ext {
    graaljsVersion = "24.2.2"// 22.3.0 24.2.1 23.0.8
}

apply from: "build_dep_ver.gradle"

rootProject.ext.assetExcludeFont = rootProject.properties.containsKey("assetExcludeFont")

architectury {
	minecraft = minecraft_version
}

configure(subprojects) {
	apply plugin: "dev.architectury.loom"

	loom {
		silentMojangMappingsLicense()
	}

	configurations {
		shadowCommon
	}

	dependencies {
		compileOnly("com.github.stuxuhai:jpinyin:1.1.7")
		implementation 'org.joml:joml:+'
		compileOnly("me.shedaniel.cloth:basic-math:+")
		annotationProcessor 'systems.manifold:manifold-preprocessor:+'
		minecraft "com.mojang:minecraft:${minecraft_version}"
		mappings parchment_version == "" ? loom.officialMojangMappings() : loom.layered() {
			officialMojangMappings()
			parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
		}
		implementation files("../checkouts/${minecraft_version}/mtr-common.jar")
		implementation "org.msgpack:msgpack-core:${rootProject.messagepack_version}"

		compileOnly("org.graalvm.polyglot:polyglot:${graaljsVersion}")
		compileOnly("org.graalvm.polyglot:js:${graaljsVersion}")
		compileOnly("org.graalvm.truffle:truffle-api:${graaljsVersion}")
		compileOnly("org.graalvm.truffle:truffle-runtime:${graaljsVersion}")

		if (name == "fabric") {
			if (!project.hasProperty('excludeGraal') || !project.property('excludeGraal').toBoolean()) {
				shadowCommon("org.graalvm.polyglot:polyglot:${graaljsVersion}")
				shadowCommon("org.graalvm.polyglot:js:${graaljsVersion}")

				shadowCommon("org.graalvm.truffle:truffle-api:${graaljsVersion}")
				shadowCommon("org.graalvm.truffle:truffle-runtime:${graaljsVersion}")
			}
			shadowCommon("com.github.stuxuhai:jpinyin:1.1.7")
		}
	}

	build.finalizedBy(mergeJars)
	assemble.finalizedBy(mergeJars)
}

// 1. Задача по скачиванию библиотек MTR 4
task setupLibrary() {
	String url = "https://aphrodite281.github.io/Minecraft-Transit-Railway-4.0.x/lib/" + minecraft_version + "/"

	doLast { // Меняем doFirst на doLast, чтобы скачивание происходило в момент выполнения задачи
		// Создаем директорию, если её нет
		file("checkouts/${minecraft_version}").mkdirs()

		download {
			src "${url}mtr-common.jar"
			dest "checkouts/${minecraft_version}/mtr-common.jar"
		}
		download {
			src "${url}mtr-fabric.jar"
			dest "checkouts/${minecraft_version}/mtr-fabric.jar"
		}
		download {
			src "${url}mtr-forge.jar"
			dest "checkouts/${minecraft_version}/mtr-forge.jar"
		}
		download {
			src "${url}files.zip"
			dest "checkouts/${minecraft_version}/files.zip"
		}
	}
}

// 2. Изолированная задача генерации маппингов (только латиница!)
task codegenMappings() {
    dependsOn setupLibrary

    doLast {
        if (!file("checkouts/${minecraft_version}/files.zip").exists()) {
            throw new GradleException("Маппинги не найдены! Сначала запустите задачу setupLibrary.")
        }

        delete "fabric/src/main/java/cn/zbx1425/mtrsteamloco/mappings"
        delete "forge/src/main/java/cn/zbx1425/mtrsteamloco/mappings"

        copy {
            from(zipTree("checkouts/${minecraft_version}/files.zip")) {
                eachFile { file -> file.relativePath = new RelativePath(true, file.relativePath.segments.drop(1) as String[]) }
            }
            into "common/src/main/java/cn/zbx1425/mtrsteamloco/mappings"
            filter(ReplaceTokens, tokens: ["package": "cn.zbx1425.mtrsteamloco.mappings; import mtr.mappings.*"])
        }

        ant.path { ant.fileset(dir: "common/src/main/java/cn/zbx1425/mtrsteamloco/mappings", includes: "Fabric*.java") }.list().each {
            ant.move(file: it, todir: "fabric/src/main/java/cn/zbx1425/mtrsteamloco/mappings")
        }

        ant.path { ant.fileset(dir: "common/src/main/java/cn/zbx1425/mtrsteamloco/mappings", includes: "Forge*.java") }.list().each {
            ant.move(file: it, todir: "forge/src/main/java/cn/zbx1425/mtrsteamloco/mappings")
        }

        ant.delete(dir: "common/src/main/java/cn/zbx1425/mtrsteamloco/mappings")
    }
}

// 4. Жестко привязываем к компиляции (тоже исправил на латиницу)
configure(subprojects) {
    tasks.withType(JavaCompile) {
        dependsOn rootProject.tasks.codegenMappings
    }
}
// 3. Чистим сам блок build от генерации кода, оставляя только копирование модов в run/mods
build {
	// Переносим генерацию BuildConfigTemplate в правильное русло
	copy {
		outputs.upToDateWhen { false }
		from "common/src/main/BuildConfigTemplate.java"
		into "common/src/main/java/cn/zbx1425/mtrsteamloco"
		filter(ReplaceTokens, tokens: [
				"version": rootProject.mod_version + "+" + minecraft_version,
				"protocol_version": rootProject.mod_protocol_version,
				"build_time": Instant.now().epochSecond.toString()
		])
		rename "(.+)Template.java", "\$1.java"
	}

	copy {
		from "checkouts/${minecraft_version}/mtr-fabric.jar"
		into "fabric/run/mods"
	}

	copy {
		from "checkouts/${minecraft_version}/mtr-forge.jar"
		into "forge/run/mods"
	}

	ant.delete(dir: "forge/build/libs")
}

// 4. ЖЕСТКО привязываем генерацию исходников ко всем задачам компиляции Java
configure(subprojects) {
	tasks.withType(JavaCompile) {
		dependsOn rootProject.tasks.codegenMappings
	}
}

tasks.named('build') {
    mustRunAfter 'setupLibrary'  // 强制顺序
}

configure(allprojects) {
	apply plugin: "architectury-plugin"

	version = rootProject.mod_version + "+" + minecraft_version
	group = project.maven_group

    repositories {
        maven { url = "https://maven.terraformersmc.com/" }
        maven { url = "https://maven.parchmentmc.org/" }
        maven { url = "https://maven.shedaniel.me/" }
        maven { url = "https://repo1.maven.org/maven2/" }

        // Наши спасительные зеркала вместо упавшего Форджа:
        maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
        maven { url = "https://modmaven.dev/" }
        maven { url = "https://maven.blamejared.com/" }
    }

	tasks.withType(JavaCompile) {
		options.encoding = "UTF-8"
    	options.incremental = true;
		

		if (minecraft_main_version == 16) {
			def targetVersion = 8
			if (JavaVersion.current().isJava9Compatible()) {
				options.release.set(targetVersion)
			}
		} else if (minecraft_main_version == 17) {
			options.release.set(16)
		} else {
			options.release.set(17)
		}

        options.compilerArgs += ['-Xplugin:Manifold', '-AMC_VERSION=' + minecraft_version_int]
		if (project.hasProperty("debug") && project.property('debug').toBoolean()) {
			options.compilerArgs += ['-ADEBUG=true']
		}
	}
}

forgix {
	group = "cn.zbx1425"
	mergedJarName = "MTR-ANTE" + "-" + rootProject.mod_version + "+" + minecraft_version + ".jar"
	outputDir = "build/"

	forge {
		projectName = "forge"
		jarLocation = "build/libs/forge" + "-" + rootProject.mod_version + "+" + minecraft_version + ".jar"
	}

	fabric {
		projectName = "fabric"
		jarLocation = "build/libs/fabric" + "-" + rootProject.mod_version + "+" + minecraft_version + ".jar"
	}
}

configure(subprojects) {
	tasks.withType(JavaCompile) {
		dependsOn rootProject.tasks.named('codegenMappings')
	}
}

tasks.withType(JavaCompile) {
	outputs.cacheIf { true }
	options.incremental = true;
}
